### PR TITLE
1st commit for Login US

### PR DESCRIPTION
**Pull request by rmautia**
Added the new login function

### CODE REVIEW

**Comment by aysuahmadli** [comment]
Nice code!

**Review by Nes09 — COMMENTED** [review]
nice code

**Review by aysuahmadli — APPROVED** [review]
Nice work!

**Comment by rmautia** [comment]
Thank you :)

**Review by aysuahmadli — COMMENTED** [review]
well done!

**Review by aysuahmadli — COMMENTED** [review]
Good job!

**Pull request merged**
